### PR TITLE
Merged table of contents and upgrade to 9.2

### LINKED ISSUE #28: Update css to handle merged TOC with navigation bar
If you merge the TOC with navigation bar the titles are bold and there is a left line:
image

Which needs to be modified

### LINKED ISSUE #37: Accessibility: Add yellow highlight to selected text
To benefit users and to be consistent with other Gov.uk sites, and the current TDT, if possible we should highlight selected text in yellow. See attached.

Screenshot 2023-06-05 at 14 09 44

### PR DESCRIPTION
**Pull request by gwionap**
- Updated stylesheet to fix issues with merged ToC and navigation. (Fixes #28)
- Also added text highlighting on press of links. (Fixes #37)

### CODE REVIEW

**Comment by SoumayaMauthoorMOJ** [comment]
Thanks @gwionap !  I should have explained that I would like to limit the number of partials we create to limit the amount of code we maintain and to make it easier to upgrade to new versions of mkdocs-material. So for example tabs-item.html was only temporary until the mkdocs-material made some changes (see https://github.com/squidfunk/mkdocs-material/pull/5138). Did you try to see if there was a way of making the changes just by updating the stylesheet? Also I hadn't realised the change was going to affect tabs_items otherwise I would have told you to wait until 9.2 is released (sorry!).

**Comment by gwionap** [comment]
The partials are only there to implement #37 as I needed a `<span>` element to enclose the title so that the yellow highlighting only applies to the text. Via css I could only clip the background to the content box. I can remove it if you'd rather tackle that seperately.

**Comment by SoumayaMauthoorMOJ** [comment]
Hey @gwionap made a few changes:

1. Removed the partials. The highlighting stills works mostly well
2. Upgrade to 9.2
3. Made the styling look like https://design-system.service.gov.uk/styles/layout/:
image
by using the code from the DBT team: https://data-workspace.docs.trade.gov.uk/development/running-locally/
4. Checked the layout works without tabs:
image
5. Fixed #16 by deleting the main panel section in the css

Would you mind reviewing? I did notice that longer subheadings don't carry over nicely so we will need to make the titles are nice and short:
image

**Review by SoumayaMauthoorMOJ — APPROVED** [review]

**Comment by gwionap** [comment]
@SoumayaMauthoorMOJ - happy with those changes. Very neat fix for the scrolling issue.

**Pull request merged**
